### ISSUE TITLE
we should skip generated classes

### ISSUE THREAD

**Issue by adaptun** [intersystems-ru/cache-tort-git#36]
reported by @iColdheart and @dmitry-zasypkin

**Comment by eduard93** [comment]
why?

**Comment by dmitry-zasypkin** [comment]
why not?) everybody do this...

**Comment by adaptun** [comment]
@eduard93 do you need not to skip it?

**Comment by tiago-sistema** [comment]
This was tested Implementation in Caché 2013.1.1? I have problems when project import in %SYS, and error triggered: %SourceControl.Git.Utils.1.INT(408) ERROR #1054: Invalid expression

**Comment by adaptun** [comment]
@tiago-sistema please open a new issue in such cases. I did it this time -- https://github.com/intersystems-ru/cache-tort-git/issues/39

**Comment by bspead** [comment]
Generated Classes should always be skipped for source control hooks as generated classes are artifacts which are created by some action performed on other configuration items already in source control.  Since that generation could differ from version to version of the DB, putting generated items into source control is a mistake because:
1) They will be overwritten when the source configuration items are recompiled
2) They could be incompatible with newer versions of the DB
A great example of this would be classes generated by a SOAP Service or Client.  These shouldn't be added to source control but should be generated automatically when the main source for these interfaces are compiled.
Sorry to be late to the party, but I wanted to clarify this :)
